FROM node:alpine
#RUN mkdir /app
#RUN chown node:node /app
#USER node
WORKDIR '/app'

#RUN chown -R 1000:1000 /app

#USER 1000

COPY ./package.json ./

RUN yarn install

#RUN yarn install axios --save

COPY ./ ./

CMD ["yarn", "run", "start"]