FROM node:alpine
#RUN mkdir /app
#RUN chown node:node /app
#USER node
WORKDIR '/app'

#RUN chown -R 1000:1000 /app

#USER 1000

COPY ./package.json ./

RUN yarn install

#RUN yarn install axios --save

COPY ./ ./

CMD ["yarn", "run", "start"]


FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/build /usr/share/nginx/html