sudo: required

services:
    - docker

# Creates a build to run the tests
before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client


# Runs tests
scripts:
    - docker run -e CI=true react-test npm run test


after_success:
# Build the PROD ready images
    - docker build -t sukumarpradhan/multi-client ./client
    - docker build -t sukumarpradhan/multi-nginx ./nginx
    - docker build -t sukumarpradhan/multi-server ./server
    - docker build -t sukumarpradhan/multi-worker ./worker
  
# Log in to Dockerhub
    - echo "$DHUB_PASSWD" | docker login -u "$DHUB_ID" --password-stdin

# Push Images to DHub 
    - docker push sukumarpradhan/multi-client
    - docker push sukumarpradhan/multi-nginx
    - docker push sukumarpradhan/multi-server
    - docker push sukumarpradhan/multi-worker