sudo: required

services:
    - docker

# Creates a build to run the tests
before_install:
    -docker build -t react-test -f ./client/Dockerfile.dev ./client


# Runs tests
scripts:
    - docker run CI=true -t react-test npm test


after_success:
# Build the PROD ready images
    - docker build -t multi-client ./client
    - docker build -t multi-nginx ./nginx
    - docker build -t multi-server ./server
    - docker build -t multi-worker ./worker
  
# Log in to Dockerhub
    - echo "$DHUB_PASSWD" | docker login -u "$DHUB_ID" --password-stdin

# Push Images to DHub
    - docker push multi-client
    - docker push multi-nginx
    - docker push multi-server
    - docker push multi-worker